services:
  moviepickarr:
    container_name: moviepickarr
    image: ghcr.io/nuxencs/moviepickarr
    restart: unless-stopped
    ports:
      - "3030:3030"
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Etc/UTC
      TMDB_API_KEY: <your_key>
    volumes:
      - ~/.config/moviepickarr:/app
